task: detection

model: DEIM
criterion: DEIMCriterion
postprocessor: PostProcessor

output_dir: ./outputs/deimv2_obb_sp_coco
comet_project_name: 'deimv2_obb_sp_coco'

use_focal_loss: True
eval_spatial_size: [640, 640] # h w
checkpoint_freq: 10    # save freq

## DEIM LR-Scheduler
epoches: 160 #  Total epochs: 20 for training + EMA  for 4n = 12. n=3 refers to the model size in the matched config.

lr_scheduler:
  type: MultiStepLR
  milestones: [500]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 250  # halved

lrsheduler: flatcosine
lr_gamma: 0.5
warmup_iter: 16   # 0.1 * epoches
flat_epoch: 96    # epoch // 2 + warmup_iter
no_aug_epoch: 8

DEIM:
  backbone: DINOv3STAsResAtten
  encoder: HybridEncoder
  decoder: DEIMTransformer

### backbone
HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_at: -1         # 0 default
  freeze_norm: False    # True default
  pretrained: True
  local_model_dir: ./weight/hgnetv2/

DINOv3STAs:
  name: dinov3_vits16plus # 名称参考 engine/backbone/dinov3/vision_transformer.py
  weights_path: ./ckpts/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
  interaction_indexes: [5,8,11]   # only need the [1/8, 1/16, 1/32]
  finetune: True
  conv_inplane: 64
  hidden_dim: 256

DINOv3STAsResAtten:
  name: dinov3_vits16plus # 名称参考 engine/backbone/dinov3/vision_transformer.py
  weights_path: ./ckpts/dinov3_vits16plus_pretrain_lvd1689m-7c1da9a5.pth
  interaction_indexes: []   # all layers will be used
  finetune: False
  conv_inplane: 64 # dinov3_hidden_dim/4
  hidden_dim: 256 # dinov3_hidden_dim*2/3
  adapter_type: 'sta'  # 'sta' or 'c3k2'

### encoder
HybridEncoder:
  in_channels: [256, 512, 1024] #[hidden_dim,2*hidden_dim,4*hidden_dim]或[hidden_dim,hidden_dim,hidden_dim]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024 #4*hidden_dim
  dropout: 0.
  enc_act: 'gelu'

  # cross
  expansion: 1.25
  depth_mult: 1.37
  act: 'silu'

  # New
  version: deim
  csp_type: csp2
  fuse_op: sum

### decoder
DEIMTransformer:
  box_mode: obb
  feat_channels: [256, 256, 256] #hidden_dim
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  # FFN
  dim_feedforward: 2048 # hidden_dim*8

  num_levels: 3
  num_layers: 6
  eval_idx: -1
  num_queries: 300
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 0.5 # dn obb 偏移范围，默认obb模式0.5,hbb模式1.0，不建议设置太大，太大生成的dn_box会失真，特别是在极端长宽比下会更加明显

  reg_max: 32
  reg_scale: 4
  layer_scale: 1  # 2

  num_points: [3, 6, 3] # [4, 4, 4] [3, 6, 3]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic

  # Act
  activation: silu
  mlp_act: silu


PostProcessor:
  box_mode: obb
  num_top_queries: 300


### optimizer
use_amp: True
use_ema: True
ema: # added EMA settings
  type: ModelEMA
  decay: 0.9998 # adjusted by 1 - (1 - decay) * 2
  warmups: 500 # halved
  start: 0
clip_max_norm: 0.1

optimizer:
  type: AdamW
  params:
    -
      # except norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$'
      lr: 0.00001 # 模型参数量越大，值应该越小。比如：sp:1e-5, l:0.5e-5, b:2.5e-6, hp:1.25e-6
    -
      # including norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$'
      lr: 0.00001
      weight_decay: 0.
    -
      # including norm/bn/bias except for the self.dinov3
      params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0005  # 模型参数量越大，值应该越小。比如：sp:5e-4, l:2.5e-4, b:1.25e-5, m:1.25e-5
  betas: [0.9, 0.999]
  weight_decay: 0.000125


### Loss
DEIMCriterion:
  box_mode: obb #obb or hbb
  weight_dict: {loss_mal: 1, loss_bbox: 2, loss_probiou: 5, loss_angle: 3, loss_kld: 1, loss_fgl: 0.15}
  losses: ['mal', 'boxes', 'local']
  use_yolo_probiou: true
  use_yolo_angle: true
  keep_kld: true
  angle_lambda: 3.0
  gamma: 1.5 # 值越小iou损失对mal损失影响越小，mal_iou_type!='iou'时，gamma应当设置较小值[0,0.5]，否则可设置[0,2]
  # mal_alpha: 1.5 # 负样本预测错误损失权重
  mal_iou_type: 'giou' # 仅hbb有效，mal损失iou类型: iou,giou,diou,ciou,eiou
  local_iou_type: 'giou' # 仅hbb有效，local损失iou类型: iou,giou,diou,ciou,eiou
  alpha: 0.75
  reg_max: 32

  matcher:
    type: HungarianMatcher
    box_mode: obb
    weight_dict: {cost_class: 2, cost_bbox: 2, cost_probiou: 4, cost_angle: 3, cost_chamfer: 5, late_cost_bbox: 0.25}
    alpha: 0.25
    gamma: 2.0
    # change matcher
    change_matcher: True
    iou_order_alpha: 4.0
    angle_order_alpha: 1.0
    matcher_change_epoch: 45

## Dense O2O: Mosaic + Mixup + CopyBlend
train_dataloader:
  total_batch_size: 2 # total batch size equals to gpu_nums*batch_size
  dataset:
    cache_images: disk
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: OBBZoomOut, fill: 0}
        - {type: OBBIoUCrop, p: 0.8}
        - {type: OBBSanitize, min_size: 1}
        - {type: OBBFlip}
        - {type: OBBResize, size: [640, 640]}
        - {type: OBBSanitize, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: OBBConvertBoxes, normalize: True, img_size: [640, 640]}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

      # Mosaic options
      policy:
        epoch: [4, 29, 50]   # list
        ops: ['Mosaic', 'RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
      mosaic_prob: 0.5

  collate_fn:
    base_size: 640
    # Mixup options
    mixup_prob: 0.5
    mixup_epochs: [4, 29]
    stop_epoch: 50    # epoch in [72, ~) stop `multiscales`
    # CopyBlend options
    copyblend_prob: 0.5
    copyblend_epochs: [4, 50]
    area_threshold: 100
    num_objects: 3
    with_expand: True
    expand_ratios: [0.1, 0.25]

    ema_restart_decay: 0.9999
    base_size_repeat: 4

val_dataloader:
  total_batch_size: 4 # total batch size equals to gpu_nums*batch_size
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
