__include__: [
 './dataset_custom_detection_train.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  './deimv2_common.yml',
]
  # '../base/optimizer.yml',


output_dir: ./outputs/deimv2_dinov3_h_coco

use_focal_loss: True
eval_spatial_size: [640, 640] # h w
checkpoint_freq: 5    # save freq
DEIM:
  backbone: DINOv3STAs

DINOv3STAs:
  name: dinov3_vith16plus
  weights_path: ./ckpts/dinov3_vith16plus_pretrain_lvd1689m-7c1da9a5.pth
  interaction_indexes: [15,23,31]   # only need the [1/8, 1/16, 1/32]
  finetune: False
  conv_inplane: 160 # hidden_dim/4
  hidden_dim: 640 # embed_dim*2/3

HybridEncoder:
  in_channels: [640, 640, 640]
  # intra
  hidden_dim: 640
  dim_feedforward: 2560 # hidden_dim*4

  # cross
  expansion: 1.25
  depth_mult: 1.37

DEIMTransformer:
  num_layers: 6
  eval_idx: -1
  num_levels: 3
  feat_strides: [8, 16, 32]
  feat_channels: [640, 640, 640]
  # reg_scale: 8
  hidden_dim: 640
  dim_feedforward: 2560 # hidden_dim*4 或 hidden_dim*8


# optimizer:
use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
  start: 0
clip_max_norm: 0.1
# optimizer:
#   type: AdamW
#   params:
#     -
#       # except norm/bn/bias in self.dinov3
#       params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$'
#       lr: 0.00001
#     -
#       # including norm/bn/bias in self.dinov3
#       params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$'
#       lr: 0.00001
#       weight_decay: 0.
#     -
#       # including norm/bn/bias except for the self.dinov3
#       params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
#       weight_decay: 0.

#   lr: 0.0005
#   betas: [0.9, 0.999]
#   weight_decay: 0.000125

optimizer:
  type: AdamW
  params:
    -
      # except norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$'
      lr: 0.0000025
    -
      # including norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$'
      lr: 0.0000025
      weight_decay: 0.
    -
      # including norm/bn/bias except for the self.dinov3
      params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.000125
  betas: [0.9, 0.999]
  weight_decay: 0.000125

# optimizer:
#   type: SGD
#   params:
#     -
#       # except norm/bn/bias in self.dinov3
#       params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$'
#       lr: 0.00001
#     -
#       # including norm/bn/bias in self.dinov3
#       params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$'
#       lr: 0.00001
#       weight_decay: 0.
#     -
#       # including norm/bn/bias except for the self.dinov3
#       params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
#       weight_decay: 0.

#   lr: 0.0005
#   momentum : 0.937
#   weight_decay: 0.0005


## DEIM LR-Scheduler
epoches: 81 # 72 + 2n  # Increase to search for the optimal ema

lr_scheduler:
  type: MultiStepLR
  milestones: [500]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 500

lrsheduler: flatcosine
lr_gamma: 0.5
warmup_iter: 10 # warmup end epoch
flat_epoch: 50    # flat end epoch: flat_epochs + warmup_iters
no_aug_epoch: 4 # cos end epoch: total - no_aug_epoch

## Dense O2O: Mosaic + Mixup + CopyBlend
train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        epoch: [4, 29, 50]   # list
  total_batch_size: 2 # total batch size equals to gpu_nums*batch_size
  collate_fn:
    mixup_epochs: [4, 29]
    stop_epoch: 50
    copyblend_epochs: [4, 50]
    base_size_repeat: 3

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  total_batch_size: 1 # total batch size equals to gpu_nums*batch_size